<?php
namespace App\Swim\Controllers;

use App\Core\Controller;
use App\Core\Database;

class MaintenanceController extends Controller {

    public function __construct() {
        if (session_status() === PHP_SESSION_NONE) {
            session_start();
        }
        // PROTEKSI AKSES: Hanya Master
        if (!isset($_SESSION['swim_role']) || $_SESSION['swim_role'] !== 'master') {
            header("Location: " . getenv('APP_URL') . "/swim/login");
            exit;
        }
    }

    public function system_health() {
        $pdo = Database::getInstance()->getConnection();

        // 1. LOGIKA BACKUP DATABASE
        if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['download_backup'])) {
            if (ob_get_level()) ob_end_clean();

            $tables = [];
            $stmt = $pdo->query("SHOW TABLES");
            while ($row = $stmt->fetch(\PDO::FETCH_NUM)) {
                $tables[] = $row[0];
            }

            $sqlScript = "-- DATABASE BACKUP: swim_meet\n";
            $sqlScript .= "-- DATE: " . date('Y-m-d H:i:s') . "\n";
            $sqlScript .= "-- GENERATED BY: Master Admin System\n\n";
            $sqlScript .= "SET SQL_MODE = \"NO_AUTO_VALUE_ON_ZERO\";\n";
            $sqlScript .= "START TRANSACTION;\n";
            $sqlScript .= "SET time_zone = \"+07:00\";\n\n"; 

            foreach ($tables as $table) {
                $row = $pdo->query("SHOW CREATE TABLE $table")->fetch(\PDO::FETCH_NUM);
                $sqlScript .= "\n\n-- Structure for table `$table` --\n";
                $sqlScript .= "DROP TABLE IF EXISTS `$table`;\n";
                $sqlScript .= $row[1] . ";\n\n";

                $stmtData = $pdo->query("SELECT * FROM $table");
                $columnCount = $stmtData->columnCount();
                $rowCount = $stmtData->rowCount();

                if ($rowCount > 0) {
                    $sqlScript .= "-- Dumping data for table `$table` --\n";
                    $sqlScript .= "INSERT INTO `$table` VALUES";
                    
                    $rows = $stmtData->fetchAll(\PDO::FETCH_NUM);
                    $counter = 0;
                    
                    foreach($rows as $row) {
                        $sqlScript .= "(";
                        for ($j = 0; $j < $columnCount; $j++) {
                            $row[$j] = addslashes($row[$j]);
                            $row[$j] = str_replace("\n", "\\n", $row[$j]);
                            if (isset($row[$j])) {
                                $sqlScript .= '"' . $row[$j] . '"';
                            } else {
                                $sqlScript .= '""';
                            }
                            if ($j < ($columnCount - 1)) {
                                $sqlScript .= ',';
                            }
                        }
                        $counter++;
                        $sqlScript .= ")" . ($counter < $rowCount ? ",\n" : ";\n");
                    }
                }
            }
            $sqlScript .= "\nCOMMIT;\n";

            $filename = 'backup_swimmeet_' . date('Y-m-d_His') . '.sql';
            
            header('Content-Description: File Transfer');
            header('Content-Type: application/octet-stream');
            header('Content-Disposition: attachment; filename=' . $filename);
            header('Expires: 0');
            header('Cache-Control: must-revalidate');
            header('Pragma: public');
            header('Content-Length: ' . strlen($sqlScript));
            
            echo $sqlScript;
            exit; 
        }

        // 2. LOGIKA VIEW LOGS & STATS
        $totalLogs = 0;
        $todayLog = 0;
        $dbSize = 0;
        $logs = [];
        $totalPages = 1;
        $error_msg = "";

        try {
            $limit = 50;
            $page = isset($_GET['page']) ? (int)$_GET['page'] : 1;
            $offset = ($page - 1) * $limit;

            $sqlLogs = "SELECT l.*, u.nama_lengkap, u.role 
                        FROM swim_system_logs l 
                        LEFT JOIN swim_users u ON l.user_id = u.id 
                        ORDER BY l.created_at DESC 
                        LIMIT :limit OFFSET :offset";
            $stmt = $pdo->prepare($sqlLogs);
            $stmt->bindValue(':limit', $limit, \PDO::PARAM_INT);
            $stmt->bindValue(':offset', $offset, \PDO::PARAM_INT);
            $stmt->execute();
            $logs = $stmt->fetchAll(\PDO::FETCH_ASSOC);

            $totalLogs = $pdo->query("SELECT COUNT(*) FROM swim_system_logs")->fetchColumn();
            $totalPages = ceil($totalLogs / $limit);
            $todayLog = $pdo->query("SELECT COUNT(*) FROM swim_system_logs WHERE DATE(created_at) = CURDATE()")->fetchColumn();

            $sqlSize = "SELECT ROUND(SUM(data_length + index_length) / 1024 / 1024, 2) 
                        FROM information_schema.tables 
                        WHERE table_schema = DATABASE()";
            $dbSize = $pdo->query($sqlSize)->fetchColumn();

        } catch (\PDOException $e) {
            $error_msg = "Terjadi kesalahan database: " . $e->getMessage();
        }

        return $this->view('swim/maintenance/system_health', [
            'totalLogs' => $totalLogs,
            'todayLog' => $todayLog,
            'dbSize' => $dbSize,
            'logs' => $logs,
            'totalPages' => $totalPages,
            'error_msg' => $error_msg,
            'page' => $page
        ]);
    }

    public function data_cleanup() {
        $pdo = Database::getInstance()->getConnection();
        $msg = '';
        $msgType = '';

        // --- HELPER LOGGING ---
        if (!function_exists('writeLog')) {
            function writeLog($pdo, $userId, $action, $targetId, $desc) {
                try {
                    $stmt = $pdo->prepare("INSERT INTO swim_system_logs (user_id, action_type, target_id, description, ip_address) VALUES (?, ?, ?, ?, ?)");
                    $stmt->execute([$userId, $action, $targetId, $desc, $_SERVER['REMOTE_ADDR'] ?? '0.0.0.0']);
                } catch (\Exception $e) {}
            }
        }

        // 1. HANDLE ACTION: MERGE CLUB
        if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['merge_clubs'])) {
            $sourceId = $_POST['source_club_id'];
            $targetId = $_POST['target_club_id'];

            if ($sourceId == $targetId) {
                $msg = "Klub asal dan tujuan tidak boleh sama!";
                $msgType = "error";
            } elseif (empty($sourceId) || empty($targetId)) {
                $msg = "Pilih kedua klub terlebih dahulu.";
                $msgType = "error";
            } else {
                try {
                    $pdo->beginTransaction();

                    $stmtUpdate = $pdo->prepare("UPDATE swim_swimmers SET club_id = ? WHERE club_id = ?");
                    $stmtUpdate->execute([$targetId, $sourceId]);
                    $countMoved = $stmtUpdate->rowCount();

                    $stmtName = $pdo->prepare("SELECT nama_klub FROM swim_clubs WHERE id = ?");
                    $stmtName->execute([$sourceId]);
                    $clubNameSource = $stmtName->fetchColumn();

                    $stmtName->execute([$targetId]);
                    $clubNameTarget = $stmtName->fetchColumn();

                    $pdo->prepare("DELETE FROM swim_clubs WHERE id = ?")->execute([$sourceId]);
                    $userId = $_SESSION['swim_user_id'] ?? $_SESSION['user_id'] ?? 0;
                    writeLog($pdo, $userId, 'MERGE_CLUB', $targetId, "Menggabungkan '$clubNameSource' ke '$clubNameTarget'. $countMoved atlet dipindahkan.");

                    $pdo->commit();
                    $msg = "SUKSES! Klub '$clubNameSource' telah dihapus dan $countMoved atlet dipindahkan ke '$clubNameTarget'.";
                    $msgType = "success";

                } catch (\Exception $e) {
                    $pdo->rollBack();
                    $msg = "Gagal merge: " . $e->getMessage();
                    $msgType = "error";
                }
            }
        }

        // 2. HANDLE ACTION: CLEANUP EVENT
        if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['cleanup_events'])) {
            try {
                $sql = "DELETE FROM swim_events WHERE event_status = 'Draft' AND created_at < DATE_SUB(NOW(), INTERVAL 30 DAY)";
                $stmt = $pdo->prepare($sql);
                $stmt->execute();
                $deleted = $stmt->rowCount();

                if ($deleted > 0) {
                    $userId = $_SESSION['swim_user_id'] ?? $_SESSION['user_id'] ?? 0;
                    writeLog($pdo, $userId, 'CLEANUP_EVENT', 0, "Menghapus $deleted event draft usang.");
                    $msg = "Berhasil menghapus $deleted event draft yang usang.";
                    $msgType = "success";
                } else {
                    $msg = "Tidak ada event draft usang yang ditemukan saat eksekusi.";
                    $msgType = "info";
                }
            } catch (\Exception $e) {
                $msg = "Error cleanup: " . $e->getMessage();
                $msgType = "error";
            }
        }

        // --- DATA UNTUK VIEW ---
        $clubs = $pdo->query("SELECT id, nama_klub, kota FROM swim_clubs ORDER BY nama_klub ASC")->fetchAll(\PDO::FETCH_ASSOC);

        $oldDrafts = [];
        try {
            $oldDrafts = $pdo->query("SELECT * FROM swim_events WHERE event_status = 'Draft' AND created_at < DATE_SUB(NOW(), INTERVAL 30 DAY)")->fetchAll(\PDO::FETCH_ASSOC);
        } catch (\Exception $e) {}

        return $this->view('swim/maintenance/data_cleanup', [
            'msg' => $msg,
            'msgType' => $msgType,
            'clubs' => $clubs,
            'oldDrafts' => $oldDrafts
        ]);
    }
}
